### ISSUE TITLE
bug: @stencil/no-unused-watch reporting errors after eslint v8 update

### ISSUE THREAD

**Issue by laddi-netapp** [stencil-community/stencil-eslint#59]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-eslint/issues) that already report this problem, without success.

### Stencil ESLint Version

v0.3.1

### Current Behavior

After updating `eslint` to `v8.x` I'm now getting lint errors on `@stencil/no-unused-watch` with message: `Watch decorator @Watch("xxx") is not matching with any @Prop() or @State()`.

This happens with all instances of `@Watch` in my codebase.

![image](https://user-images.githubusercontent.com/49026685/138428773-a5a25224-220e-4cd1-99d9-712fa91c6e5c.png)

### Expected Behavior

There should only be a lint error when there is no matching `@Prop` or `@State` to correspond with the `@Watch`.

### Steps to Reproduce

Update `eslint` to `v8.x`, add `@stencil/eslint-plugin` and create a component with a `@Prop` and then add a `@Watch` for it.

**Comment by pranav-js** [comment]
facing same issue related to decorators linting :(

**Comment by raphaelpor** [comment]
Solved on #84.
