### ISSUE TITLE
bug: lot of rules not working

### ISSUE THREAD

**Issue by pranav-js** [stencil-community/stencil-eslint#69]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-eslint/issues) that already report this problem, without success.

### Stencil ESLint Version

latest

### Current Behavior

here is my `.eslintrc.js`

```js
module.exports = {
  extends: ['../../.eslintrc.json'],
  ignorePatterns: ['!**/*'],
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: __dirname,
        sourceType: 'module',
      },
      extends: ['plugin:@stencil/recommended'],
      rules: {
        '@stencil/decorators-context': 'off',
        '@stencil/no-unused-watch': 'off',
        '@stencil/decorators-style': [
          'error',
          {
            prop: 'inline',
            state: 'inline',
            element: 'inline',
            event: 'inline',
            method: 'multiline',
            watch: 'multiline',
            listen: 'multiline',
          },
        ],
        '@stencil/element-type': 'error',
        '@stencil/host-data-deprecated': 'error',
        '@stencil/methods-must-be-public': 'error',
        '@stencil/own-methods-must-be-private': 'error',
        '@stencil/own-props-must-be-private': 'error',
        '@stencil/prefer-vdom-listener': 'error',
        '@stencil/props-must-be-public': 'error',
        '@stencil/props-must-be-readonly': 'error',
        '@stencil/render-returns-host': 'error',
        '@stencil/required-jsdoc': 'error',
        '@stencil/reserved-member-names': 'error',
        '@stencil/single-export': 'error',
        '@stencil/strict-mutable': 'error',
      },
    },
  ],
};

```

rules like 

         prop: 'inline',
        '@stencil/required-jsdoc': 'error',
 
 // had to turn off these
        '@stencil/decorators-context': 'off',
        '@stencil/no-unused-watch': 'off',
 
 Don't work! 
 
 I am using nx mono repo with eslint 8.0

### Expected Behavior

all rules should work with this config

### Steps to Reproduce

please check confile for this and run eslint command

### Code Reproduction URL

just try with fresh nx repo + stencil

**Comment by raphaelpor** [comment]
I am having the same issue.
I tried to check the unit tests of this repo and for some reason, the rules work here, but not in my own project.

Another test I made was by updating all the dev dependencies of this repo and build the stencil-eslint plugin again. But this also doesn't fix the issue.

I am also using ESLint 8.0.

Any thoughts?

**Comment by pranav-js** [comment]
the plugin seems to be not on eslint 8.  this needs to be looked at.  @rwaskiewicz might know about this. The last update was a year ago.

**Comment by rwaskiewicz** [comment]
Hey all,

We opened up a call-to-action to see if anyone was willing/able to help maintain this package as a part of the Stencil Community initiative a month or so ago, but never got any interest. I've created https://github.com/ionic-team/stencil-eslint/issues/76 as a last-chance effort to see if anyone's interested

**Comment by raphaelpor** [comment]
@rwaskiewicz I have sent a message in the channel. I hope we can start some talks on how to move forward with that. 🙌

**Comment by raphaelpor** [comment]
#84 Should fix that.

**Comment by raphaelpor** [comment]
Hello @pranav-js, 👋 
Thanks for your report!
We just published a test version on NPM with the ESLint 8 update.
Could you please try it out and see if it fixes your issues?

To install: `npm install @stencil-community/eslint-plugin@0.5.0-alpha.1`.

We might release a proper version after our internal tests.
