### ISSUE TITLE
feat: EsLint v8

### ISSUE THREAD

**Issue by konrad-kinesso** [stencil-community/stencil-eslint#74]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-eslint/issues) that already include this feature request, without success.

### Describe the Feature Request

Please update EsLint

### Describe the Use Case

I want to use stencil rules in conjunction with @nrwl/eslint-plugin-nx ^14

**Comment by pranav-js** [comment]
links to #76

**Comment by elizabethsjudd** [comment]
Is there any update on when this might be completed? Even with using ES7, this is breaking with TS 4.9.4.

**Comment by raphaelpor** [comment]
Added a new PR for that: #84

**Comment by raphaelpor** [comment]
Hello @elizabethsjudd and @konrad-kinesso, 👋 
Thanks for your report!
We just published a test version on NPM with the ESLint 8 update.
Could you please try it out and see if it fixes your issues?

To install: npm install @stencil-community/eslint-plugin@0.5.0-alpha.1.

We will release a proper version after our internal tests.

**Comment by rschaufler** [comment]
@raphaelpor i have `@stencil-community/eslint-plugin@0.5.0-alpha.1` running with `@stencil/core 3.0.0`, `typescript 4.9.5` and  `eslint 8.32.0`. I briefly tested it, and it works well as far as i can see.

**Comment by raphaelpor** [comment]
Great @rschaufler!
You can also use the version  `@stencil-community/eslint-plugin@0.5.0` which is now released on npm.

I would suggest closing this issue next week if we don't get any new replies.

Big thanks for testing it! ❤️
