### ISSUE TITLE
bug:  Received “stencil-maintainers-put-an-invalid-version-intentionally-if-this-errors-please-raise-an-issue" message while running eslint with @stencil/eslint-plugin v0.4.0

### ISSUE THREAD

**Issue by bjankord** [stencil-community/stencil-eslint#77]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-eslint/issues) that already report this problem, without success.

### Stencil ESLint Version

0.4.0

### Current Behavior

When running eslint with @stencil/eslint-plugin v0.4.0, I see a lot of " got “stencil-maintainers-put-an-invalid-version-intentionally-if-this-errors-please-raise-an-issue" messages

### Expected Behavior

When running eslint with @stencil/eslint-plugin, I should not see any "stencil-maintainers-put-an-invalid-version-intentionally-if-this-errors-please-raise-an-issue" messages

### Steps to Reproduce

Updated @stencil/eslint-plugin from `^0.3.1` to `^0.4.0`

### Code Reproduction URL

N/A

**Comment by raphaelpor** [comment]
@bjankord Can you still reproduce the issue when using v0.5.0?

**Comment by raphaelpor** [comment]
Closing for not being able to reproduce.
