### ISSUE TITLE
feat: Clarify which NPM package to use

### ISSUE THREAD

**Issue by niklas2810** [stencil-community/stencil-eslint#88]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/stencil-community/stencil-eslint/issues) that already include this feature request, without success.

### Describe the Feature Request

Hey there! I am opening this as a feature request since this is something which I think needs change, but is not a bug per se.

I noticed that the eslint plugin was moved to the stencil-community organization (#76 ), and with that there is a new name associated: `@stencil-community/eslint-plugin`.

That makes sense, but in my mind its very confusing that the original package `@stencil/eslint-plugin` (https://www.npmjs.com/package/@stencil/eslint-plugin) is still online, without any notice in its package info. The link is also still the ionic-team one, even though it automatically redirects to this repo.

### Describe the Use Case

I'm not very experienced with publishing NPM packages - so please forgive me if there is no easy solution for that - but is there a way we could add some kind of deprecation warning to the original package on npmjs.com? Otherwise you have to check the link to the GitHub repo to find out that the package has moved.

### Describe Preferred Solution

Add a deprecation warning to the original package.

### Describe Alternatives

Add a hint in the README of this repository, so that at least anyone visiting from npmjs.com immediately sees that the package has moved.

**Comment by raphaelpor** [comment]
@rwaskiewicz Can we do something about it in the original package?

**Comment by raphaelpor** [comment]
Big thanks @rwaskiewicz! I will close this issue then. :)
