### ISSUE TITLE
feat: upgrade to TypeScript 5

### ISSUE THREAD

**Issue by rschaufler** [stencil-community/stencil-eslint#90]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/stencil-community/stencil-eslint/issues) that already include this feature request, without success.

### Describe the Feature Request

Update the required TypeScript version to 5

### Describe the Use Case

As of now, this plugin is not compatible to @stencil/core 3.3.x. @stencil/core 3.3.x. introduced a minimum requirement for TypeScript 5.

See: https://github.com/ionic-team/stencil/blob/main/package.json#L125

**Comment by mfeltscher** [comment]
I opened a merge request for this: https://github.com/stencil-community/stencil-eslint/pull/92

**Comment by RogierKonings** [comment]
> I opened a merge request for this: #92

Hopefully this can be merged soon, waiting for this MR.

**Comment by raphaelpor** [comment]
Solved on #97.
Thanks for your contributions! 🙏
