### ISSUE TITLE
feat: support @typescript-eslint/eslint-plugin ^6.0.0

### ISSUE THREAD

**Issue by cmotsn** [stencil-community/stencil-eslint#95]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/stencil-community/stencil-eslint/issues) that already include this feature request, without success.

### Describe the Feature Request

`@typescript-eslint/eslint-plugin` has released a new version 6.0.0, but this plugin only support up to 5.x.x, which prevent projects from upgrading `eslint-plugin` to the latest version.

See the [`eslint-plugin` 6.0.0 release announcement](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/) for more details on the changes (some of which might impact plugins).

### Describe the Use Case

I want to be able to keep up-to-date dependencies.

**Comment by raphaelpor** [comment]
Solved on #97.
Thanks for your contribution @cmotsn. 🙏
